openapi: 3.0.3
info:
  title: Twitter SWE - OpenAPI 3.0
  description: |-
    A simple server to collect tweets and display them in a minimal webpage.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api/
tags:
  - name: Tweets
    description: APIs to obtain tweets
paths:
  /chess/games:
    post:
      tags:
        - Chess
      summary: Create a chess game
      description: ''
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChessGame'
        '400':
          description: Error
  /chess/games/{gameID}/move:
    post:
      tags:
        - Chess
      summary: Make a move in a chess game
      description: ''
      parameters:
        - name: gameID
          in: path
          required: true
          description: The id of the chess game.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChessMove'
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ChessGame'
        '400':
          description: Error
  /search/{query}:
    get:
      tags:
        - Tweets
      summary: Get recent tweets
      description: ''
      parameters:
        - name: query
          in: path
          required: true
          description: The query to search.
          schema:
            type: string
        - name: max_results
          in: query
          description: The maximum number of tweets.
          schema:
            type: integer
            minimum: 10
            maximum: 100
        - name: start_time
          in: query
          description: The oldest UTC timestamp from which the Tweets will be provided.
          schema:
            type: string
            format: date-time
        - name: end_time
          in: query
          description: The newest, most recent UTC timestamp to which the Tweets will be provided.
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tweet'
        '400':
          description: Error
components:
  schemas:
    ChessGame:
      type: object
      properties:
        gameId:
          type: integer
        lastMoveLegal:
          type: boolean
        gameOver:
          type: boolean
        gameResult:
          type: string
          enum: [u, w, b, d]
          description: >
            Possible values: "u" undefined, "w" white win, "b" black win, "d" draw
        fen:
          type: string
        turn:
          type: string
    ChessMove:
      type: object
      properties:
        from:
          type: string
        to:
          type: string
        promotion:
          type: string
      required:
        - from
        - to
    Place:
      type: object
      properties:
        id:
          type: string
        full_name:
          type: string
        geo:
          type: object
    User:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        username:
          type: string
        profile_image_url:
          type: string
    Tweet:
      type: object
      properties:
        id:
          type: string
        text:
          type: string
        created_at:
          type: string
        author:
          $ref: '#/components/schemas/User'
        place:
          $ref: '#/components/schemas/Place'
        next_token: # Only in the last tweet when there are older results
          type: string