openapi: 3.0.3
info:
  title: Twitter SWE - OpenAPI 3.0
  description: |-
    A simple server to collect tweets and display them in a minimal webpage.
  version: 1.0.0
servers:
  - url: https://url.delle.api/api/v3
tags:
  - name: WinningTweets
    description: APIs to visualize winning tweets
paths:
  /api/v1/winning:
    get:
      tags:
        - WinningTweets
      summary: Get all winning tweets
      description: ''
      operationId: winningTweets
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  properties:
                    tweet_url:
                      type: string
                    tweet_text:
                      type: string
        '404':
          description: Tweets not found
  